stages:
  - build
  - test
  - deploy

variables:
  PIP_EXTRA_INDEX_URL: 'https://pypi.python.org/simple'
  PYTHON_VERSION: '3.8.0'

build:
  stage: build
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install exifread
  artifacts:
    paths:
      - main.py

test:
  stage: test
  script:
    - source venv/bin/activate
    - python3 -m unittest discover -s tests
  dependencies:
    - build

deploy:
  stage: deploy
  script:
    - echo "Deploying to production"
  only:
    - main
