stages:
  - build
  - test
  - deploy

variables:
  PIP_EXTRA_INDEX_URL: 'https://pypi.python.org/simple'
  PYTHON_VERSION: '3.8.0'

before_script:
  - apt update -qq
  - apt install -y python3-venv
  - python3 -m venv venv
  - venv/bin/python -m pip install --upgrade pip
  - venv/bin/pip install exifread

build:
  stage: build
  script:
    - echo "Building"
  artifacts:
    paths:
      - main.py

test:
  stage: test
  script:
    - venv/bin/python -m unittest discover -s tests
  dependencies:
    - build

deploy:
  stage: deploy
  script:
    - echo "Deploying to production"
  only:
    - main
